import type { BoardSpace } from './board.js';

interface CP { name: string; nameAr: string; }

function buildBoard(
  props: CP[],
  railroads: [CP, CP, CP, CP],
  utilities: [CP, CP],
  tax1: CP & { amount: number },
  tax2: CP & { amount: number },
  chance: CP,
  community: CP,
): BoardSpace[] {
  const p = props;
  const r = railroads;
  const u = utilities;
  return [
    { index: 0,  name: 'GO',             nameAr: 'انطلق',          type: 'go' },
    { index: 1,  ...p[0],  type: 'property', price: 600,  rent: [40,200,600,1800,3200,5000],    houseCost: 500,  hotelCost: 500,  mortgageValue: 300,  colorGroup: 'brown' },
    { index: 2,  ...community,            type: 'community' },
    { index: 3,  ...p[1],  type: 'property', price: 800,  rent: [60,300,900,2700,4000,5500],    houseCost: 500,  hotelCost: 500,  mortgageValue: 400,  colorGroup: 'brown' },
    { index: 4,  name: tax1.name, nameAr: tax1.nameAr, type: 'tax', taxAmount: tax1.amount },
    { index: 5,  ...r[0],  type: 'railroad', price: 2000, mortgageValue: 1000, railroadRent: [250,500,1000,2000] },
    { index: 6,  ...p[2],  type: 'property', price: 1000, rent: [60,300,900,2700,4000,5500],    houseCost: 500,  hotelCost: 500,  mortgageValue: 500,  colorGroup: 'lightblue' },
    { index: 7,  ...chance,               type: 'chance' },
    { index: 8,  ...p[3],  type: 'property', price: 1000, rent: [60,300,900,2700,4000,5500],    houseCost: 500,  hotelCost: 500,  mortgageValue: 500,  colorGroup: 'lightblue' },
    { index: 9,  ...p[4],  type: 'property', price: 1200, rent: [80,400,1000,3000,4500,6000],   houseCost: 500,  hotelCost: 500,  mortgageValue: 600,  colorGroup: 'lightblue' },
    { index: 10, name: 'Jail',            nameAr: 'السجن',          type: 'jail' },
    { index: 11, ...p[5],  type: 'property', price: 1400, rent: [100,500,1500,4500,6250,7500],  houseCost: 1000, hotelCost: 1000, mortgageValue: 700,  colorGroup: 'pink' },
    { index: 12, ...u[0],  type: 'utility',  price: 1500, mortgageValue: 750 },
    { index: 13, ...p[6],  type: 'property', price: 1400, rent: [100,500,1500,4500,6250,7500],  houseCost: 1000, hotelCost: 1000, mortgageValue: 700,  colorGroup: 'pink' },
    { index: 14, ...p[7],  type: 'property', price: 1600, rent: [120,600,1800,5000,7000,9000],  houseCost: 1000, hotelCost: 1000, mortgageValue: 800,  colorGroup: 'pink' },
    { index: 15, ...r[1],  type: 'railroad', price: 2000, mortgageValue: 1000, railroadRent: [250,500,1000,2000] },
    { index: 16, ...p[8],  type: 'property', price: 1800, rent: [140,700,2000,5500,7500,9500],  houseCost: 1000, hotelCost: 1000, mortgageValue: 900,  colorGroup: 'orange' },
    { index: 17, ...community,            type: 'community' },
    { index: 18, ...p[9],  type: 'property', price: 1800, rent: [140,700,2000,5500,7500,9500],  houseCost: 1000, hotelCost: 1000, mortgageValue: 900,  colorGroup: 'orange' },
    { index: 19, ...p[10], type: 'property', price: 2000, rent: [160,800,2200,6000,8000,10000], houseCost: 1000, hotelCost: 1000, mortgageValue: 1000, colorGroup: 'orange' },
    { index: 20, name: 'Free Parking',    nameAr: 'وقوف مجاني',     type: 'free_parking' },
    { index: 21, ...p[11], type: 'property', price: 2200, rent: [180,900,2500,7000,8750,10500], houseCost: 1500, hotelCost: 1500, mortgageValue: 1100, colorGroup: 'red' },
    { index: 22, ...chance,               type: 'chance' },
    { index: 23, ...p[12], type: 'property', price: 2200, rent: [180,900,2500,7000,8750,10500], houseCost: 1500, hotelCost: 1500, mortgageValue: 1100, colorGroup: 'red' },
    { index: 24, ...p[13], type: 'property', price: 2400, rent: [200,1000,3000,7500,9250,11000], houseCost: 1500, hotelCost: 1500, mortgageValue: 1200, colorGroup: 'red' },
    { index: 25, ...r[2],  type: 'railroad', price: 2000, mortgageValue: 1000, railroadRent: [250,500,1000,2000] },
    { index: 26, ...p[14], type: 'property', price: 2600, rent: [220,1100,3300,8000,9750,11500], houseCost: 1500, hotelCost: 1500, mortgageValue: 1300, colorGroup: 'yellow' },
    { index: 27, ...p[15], type: 'property', price: 2600, rent: [220,1100,3300,8000,9750,11500], houseCost: 1500, hotelCost: 1500, mortgageValue: 1300, colorGroup: 'yellow' },
    { index: 28, ...u[1],  type: 'utility',  price: 1500, mortgageValue: 750 },
    { index: 29, ...p[16], type: 'property', price: 2800, rent: [240,1200,3600,8500,10250,12000], houseCost: 1500, hotelCost: 1500, mortgageValue: 1400, colorGroup: 'yellow' },
    { index: 30, name: 'Go to Jail',      nameAr: 'اذهب إلى السجن', type: 'go_to_jail' },
    { index: 31, ...p[17], type: 'property', price: 3000, rent: [260,1300,3900,9000,11000,12750],  houseCost: 2000, hotelCost: 2000, mortgageValue: 1500, colorGroup: 'green' },
    { index: 32, ...p[18], type: 'property', price: 3200, rent: [280,1500,4500,10000,12000,14000],  houseCost: 2000, hotelCost: 2000, mortgageValue: 1600, colorGroup: 'green' },
    { index: 33, ...community,            type: 'community' },
    { index: 34, ...p[19], type: 'property', price: 3400, rent: [300,1600,4800,10500,12500,14750],  houseCost: 2000, hotelCost: 2000, mortgageValue: 1700, colorGroup: 'green' },
    { index: 35, ...r[3],  type: 'railroad', price: 2000, mortgageValue: 1000, railroadRent: [250,500,1000,2000] },
    { index: 36, ...chance,               type: 'chance' },
    { index: 37, ...p[20], type: 'property', price: 3800, rent: [400,1800,5500,12500,15500,18000],  houseCost: 2000, hotelCost: 2000, mortgageValue: 1900, colorGroup: 'darkblue' },
    { index: 38, name: tax2.name, nameAr: tax2.nameAr, type: 'tax', taxAmount: tax2.amount },
    { index: 39, ...p[21], type: 'property', price: 4000, rent: [500,2000,6000,14000,17000,20000],  houseCost: 2000, hotelCost: 2000, mortgageValue: 2000, colorGroup: 'darkblue' },
  ];
}

// ─── Industry: Silicon Souq (Tech) ────────────────────────────────────────────
const TECH_BOARD = buildBoard(
  [
    { name: 'Maktobb',        nameAr: 'مكتوب' },
    { name: 'Wamda',          nameAr: 'وامضة' },
    { name: 'Fetchrr',        nameAr: 'فيتشر' },
    { name: 'Yallaah',        nameAr: 'يلا' },
    { name: 'Anghami+',       nameAr: 'أنغامي+' },
    { name: 'Ziina Pay',      nameAr: 'زينة باي' },
    { name: 'Tabbyy',         nameAr: 'تابي' },
    { name: 'Sarwaa',         nameAr: 'ثروة' },
    { name: 'Sooq.net',       nameAr: 'سوق.نت' },
    { name: 'Noonn',          nameAr: 'نون' },
    { name: 'Careezm',        nameAr: 'كريزم' },
    { name: 'Talabaat',       nameAr: 'طلبات' },
    { name: 'HungerZ',        nameAr: 'هانقرز' },
    { name: 'Swvvl',          nameAr: 'سويفل' },
    { name: 'Jeenee',         nameAr: 'جيني' },
    { name: 'Fawwry',         nameAr: 'فوري' },
    { name: 'Baraakaa',       nameAr: 'بركة' },
    { name: 'Foodiccs',       nameAr: 'فوديكس' },
    { name: 'Unifonicc',      nameAr: 'يونيفونيك' },
    { name: 'Baytt.com',      nameAr: 'بيت.كوم' },
    { name: 'Careeym',        nameAr: 'كريم' },
    { name: 'Amazoon Arabia', nameAr: 'أمازون العرب' },
  ],
  [
    { name: 'Dubai Internet City Hub', nameAr: 'مركز دبي للإنترنت' },
    { name: 'KAFD Tech District',      nameAr: 'مجمع كافد التقني' },
    { name: 'Amman Digital Hub',       nameAr: 'مركز عمّان الرقمي' },
    { name: 'Cairo Innovation Zone',   nameAr: 'منطقة القاهرة للابتكار' },
  ],
  [
    { name: 'Gulf Cloud Network',  nameAr: 'شبكة الغيوم الخليجية' },
    { name: 'Nile Data Centres',   nameAr: 'مراكز بيانات النيل' },
  ],
  { name: 'Software License Tax', nameAr: 'ضريبة رخص البرامج',   amount: 500 },
  { name: 'Data Breach Penalty',  nameAr: 'غرامة اختراق البيانات', amount: 2000 },
  { name: 'Startup Roulette',     nameAr: 'روليت الشركات الناشئة' },
  { name: 'Enterprise Fund',      nameAr: 'صندوق المشاريع' },
);

// ─── Industry: Fashion Week (Clothing) ────────────────────────────────────────
const FASHION_BOARD = buildBoard(
  [
    { name: "Deena's Closet",  nameAr: 'خزانة دينا' },
    { name: 'Moda Siti',       nameAr: 'موضة سيتي' },
    { name: 'Sun & Saand',     nameAr: 'صن آند صاند' },
    { name: 'Brandz4Less',     nameAr: 'براندز للأقل' },
    { name: 'Trendz Mall',     nameAr: 'ترندز مول' },
    { name: 'Rivoly',          nameAr: 'ريفولي' },
    { name: 'Modanisaa',       nameAr: 'مودانيسا' },
    { name: 'Al-Modaa',        nameAr: 'المودة' },
    { name: 'Splassh',         nameAr: 'سبلاش' },
    { name: 'Level Shooes',    nameAr: 'ليفل شوز' },
    { name: 'Diyafa Fashion',  nameAr: 'ضيافة فاشون' },
    { name: 'Zaraa ME',        nameAr: 'زارا الشرق الأوسط' },
    { name: 'Mangoo ME',       nameAr: 'مانغو الشرق الأوسط' },
    { name: 'Beymannn',        nameAr: 'بيمان' },
    { name: 'H&MM ME',         nameAr: 'H&M الشرق الأوسط' },
    { name: 'Massimoo',        nameAr: 'ماسيمو' },
    { name: 'Primarkk',        nameAr: 'برايمارك' },
    { name: 'Zalandoo ME',     nameAr: 'زالاندو الشرق الأوسط' },
    { name: 'FarFetchh',       nameAr: 'فارفيتش' },
    { name: 'Net-A-Porteer',   nameAr: 'نت-أ-بورتر' },
    { name: 'Louisss Vitton',  nameAr: 'لويس فيتون' },
    { name: 'Guccii Arabia',   nameAr: 'غوتشي العربية' },
  ],
  [
    { name: 'Dubai Mall Fashion Walk',  nameAr: 'واجهة دبي مول' },
    { name: 'Riyadh Park Mall',         nameAr: 'ريياض بارك مول' },
    { name: 'The Avenues Kuwait',       nameAr: 'ذا أفنيوز الكويت' },
    { name: 'Mall of Arabia Egypt',     nameAr: 'مول أوف أرابيا' },
  ],
  [
    { name: 'Gulf Textile Mills', nameAr: 'مصانع النسيج الخليجية' },
    { name: 'Nile Cotton Co.',    nameAr: 'شركة قطن النيل' },
  ],
  { name: 'Import Duty Tax',       nameAr: 'ضريبة الاستيراد',          amount: 500 },
  { name: 'Fashion Licensing Fee', nameAr: 'رسوم ترخيص الأزياء',       amount: 2000 },
  { name: 'Style Lottery',         nameAr: 'يانصيب الستايل' },
  { name: 'Fashion Fund',          nameAr: 'صندوق الأزياء' },
);

// ─── Industry: Street Flavors (Food & Beverage) ───────────────────────────────
const FOOD_BOARD = buildBoard(
  [
    { name: 'Karak Housee',      nameAr: 'بيت الكرك' },
    { name: 'Baladii Burgers',   nameAr: 'برغر البلدي' },
    { name: 'Shawarmer',         nameAr: 'شاورمر' },
    { name: 'Al-Baiikk',        nameAr: 'البيك' },
    { name: 'Kuduu',             nameAr: 'كودو' },
    { name: 'Papa Johnzz',       nameAr: 'بابا جونز' },
    { name: "Hardee'z ME",       nameAr: 'هارديز الشرق الأوسط' },
    { name: 'Burger Bashaa',     nameAr: 'برغر باشا' },
    { name: 'Starbuckees ME',    nameAr: 'ستاربيكس الشرق الأوسط' },
    { name: 'Costa Coffii ME',   nameAr: 'كوستا كافيه' },
    { name: "Dunkin' Arabiya",   nameAr: 'دنكن العربية' },
    { name: 'Tazaa Bowl',        nameAr: 'طازة بول' },
    { name: 'Maestro Pizza',     nameAr: 'مايسترو بيتزا' },
    { name: 'Mooza Desserts',    nameAr: 'موزة للحلويات' },
    { name: 'Savola Foods',      nameAr: 'صافولا للأغذية' },
    { name: 'Agthiaa Group',     nameAr: 'أجتيا للمجموعة' },
    { name: 'Bayara Foods',      nameAr: 'بياره للأغذية' },
    { name: 'Nandoos ME',        nameAr: 'ناندوز الشرق الأوسط' },
    { name: 'Texas Chickenn ME', nameAr: 'تكساس تشيكن' },
    { name: 'KFZ Arabia',        nameAr: 'كي إف زد العربية' },
    { name: 'Almaraii',          nameAr: 'المراعي' },
    { name: "McDonald'zz ME",    nameAr: 'ماكدونالدز الشرق الأوسط' },
  ],
  [
    { name: 'Al-Khobar Food Expo Hub', nameAr: 'مركز تصدير الخبر' },
    { name: 'Jeddah Food Terminal',    nameAr: 'محطة جدة للأغذية' },
    { name: 'Dubai Food Festival Hub', nameAr: 'مركز دبي للأغذية' },
    { name: 'Cairo Distribution Hub',  nameAr: 'مركز توزيع القاهرة' },
  ],
  [
    { name: 'Gulf Cold Storage Co.', nameAr: 'شركة الخليج للتبريد' },
    { name: 'Nile Agri Supply',      nameAr: 'إمدادات النيل الزراعية' },
  ],
  { name: 'VAT on Food & Beverages', nameAr: 'ضريبة المواد الغذائية', amount: 500 },
  { name: 'Health Inspection Fine',  nameAr: 'غرامة التفتيش الصحي',   amount: 2000 },
  { name: 'Taste the Luck',          nameAr: 'تذوق الحظ' },
  { name: 'Community Kitchen Fund',  nameAr: 'صندوق المطبخ المجتمعي' },
);

// ─── Industry: Iron Desert (Defense & Weapons) ────────────────────────────────
const DEFENSE_BOARD = buildBoard(
  [
    { name: 'Tawazunn Holdings',     nameAr: 'توازن القابضة' },
    { name: 'Burkan Munitionns',     nameAr: 'بركان للذخائر' },
    { name: 'NIMRR Armored',         nameAr: 'نمر المدرعة' },
    { name: 'Al Jabbrr Systems',     nameAr: 'الجابر سيستمز' },
    { name: 'Saab ME',               nameAr: 'ساب الشرق الأوسط' },
    { name: 'Karakal Intl',          nameAr: 'قراقل الدولية' },
    { name: 'Halcoon',               nameAr: 'حلقون' },
    { name: 'Emirates Def Tech',     nameAr: 'تقنيات الدفاع الإماراتية' },
    { name: 'BAE Systms ME',         nameAr: 'BAE سيستمز' },
    { name: 'Rheinmetalll ME',       nameAr: 'راينميتال' },
    { name: 'Thalesss ME',           nameAr: 'ثاليس' },
    { name: 'L3Harriss ME',          nameAr: 'إل٣ هاريس' },
    { name: 'Raytheonn ME',          nameAr: 'ريثيون' },
    { name: 'Boeengg Defense',       nameAr: 'بوينغ دفاع' },
    { name: 'Airbus Def. ME',        nameAr: 'إيرباص دفاع' },
    { name: 'Leeonardo ME',          nameAr: 'ليوناردو' },
    { name: 'General Dyynamics ME',  nameAr: 'جنرال ديناميكس' },
    { name: 'Lockheed ME',           nameAr: 'لوكهيد' },
    { name: 'Northrop Grummann',     nameAr: 'نورثروب غرومان' },
    { name: 'Jordaan Aerospace',     nameAr: 'الفضاء الجوي الأردني' },
    { name: 'SAMII',                 nameAr: 'سامي' },
    { name: 'EDGEE Group',           nameAr: 'مجموعة إيدج' },
  ],
  [
    { name: 'Al Udeid Logistics Hub',     nameAr: 'مركز لوجستيات العديد' },
    { name: 'King Fahd Base Supply',      nameAr: 'مؤن قاعدة الملك فهد' },
    { name: 'Al Dhafra Defense Hub',      nameAr: 'مركز الدفاع الضفرة' },
    { name: 'Muwaffaq Salti Logistics',   nameAr: 'لوجستيات مفرق' },
  ],
  [
    { name: 'Gulf Explosives Testing',   nameAr: 'مختبر متفجرات الخليج' },
    { name: 'Desert Drone Test Range',   nameAr: 'ميدان طائرات الصحراء' },
  ],
  { name: 'Defense Procurement Tax', nameAr: 'ضريبة المشتريات الدفاعية', amount: 500 },
  { name: 'Arms Export License',     nameAr: 'رخصة تصدير الأسلحة',        amount: 2000 },
  { name: 'War Games Lottery',       nameAr: 'يانصيب مناورات الحرب' },
  { name: 'Defense Fund',            nameAr: 'صندوق الدفاع' },
);

// ─── Country: Kingdom of Jordan ───────────────────────────────────────────────
const JORDAN_BOARD = buildBoard(
  [
    { name: 'Tafilah',          nameAr: 'الطفيلة' },
    { name: 'Ramtha',           nameAr: 'الرمثا' },
    { name: 'Ruseifa',          nameAr: 'الرصيفة' },
    { name: 'Mafraq',           nameAr: 'المفرق' },
    { name: "Ma'an",            nameAr: 'معان' },
    { name: 'Ajloun',           nameAr: 'عجلون' },
    { name: 'Madaba',           nameAr: 'مادبا' },
    { name: 'Zarqa',            nameAr: 'الزرقاء' },
    { name: 'Karak',            nameAr: 'الكرك' },
    { name: 'Salt',             nameAr: 'السلط' },
    { name: 'Balqa',            nameAr: 'البلقاء' },
    { name: 'Irbid',            nameAr: 'إربد' },
    { name: 'Umm Qais',         nameAr: 'أم قيس' },
    { name: 'Jerash',           nameAr: 'جرش' },
    { name: 'Dead Sea Area',    nameAr: 'منطقة البحر الميت' },
    { name: 'Wadi Rum',         nameAr: 'وادي رم' },
    { name: 'Aqaba',            nameAr: 'العقبة' },
    { name: 'Petra',            nameAr: 'البتراء' },
    { name: 'Abdali District',  nameAr: 'منطقة الأبدلي' },
    { name: 'Amman East',       nameAr: 'شرق عمّان' },
    { name: 'West Amman',       nameAr: 'غرب عمّان' },
    { name: 'Amman',            nameAr: 'عمّان' },
  ],
  [
    { name: 'Queen Alia International', nameAr: 'مطار الملكة علياء الدولي' },
    { name: 'Aqaba King Hussein Airport', nameAr: 'مطار العقبة الملك حسين' },
    { name: "Ma'an Airport",            nameAr: 'مطار معان' },
    { name: 'Prince Hashim Airport',    nameAr: 'مطار الأمير هاشم' },
  ],
  [
    { name: 'Jordan Water Authority',  nameAr: 'سلطة المياه الأردنية' },
    { name: 'Jordan Electric Power',   nameAr: 'الطاقة الكهربائية الأردنية' },
  ],
  { name: 'Income Tax',        nameAr: 'ضريبة الدخل',       amount: 500 },
  { name: 'Land Transfer Tax', nameAr: 'ضريبة نقل الأراضي', amount: 2000 },
  { name: 'Desert Fortune',    nameAr: 'حظ الصحراء' },
  { name: 'Jordan Dev. Fund',  nameAr: 'صندوق التنمية الأردني' },
);

// ─── Country: Saudi Arabia ────────────────────────────────────────────────────
const SAUDI_BOARD = buildBoard(
  [
    { name: 'Dawadmi',    nameAr: 'الدوادمي' },
    { name: 'Al-Wajh',   nameAr: 'الوجه' },
    { name: 'Sakakah',   nameAr: 'سكاكا' },
    { name: 'Al Baha',   nameAr: 'الباحة' },
    { name: 'Bisha',     nameAr: 'بيشة' },
    { name: 'Najran',    nameAr: 'نجران' },
    { name: "Ha'il",     nameAr: 'حائل' },
    { name: 'Al Qatif',  nameAr: 'القطيف' },
    { name: 'Jizan',     nameAr: 'جيزان' },
    { name: 'Yanbu',     nameAr: 'ينبع' },
    { name: 'Taif',      nameAr: 'الطائف' },
    { name: 'Abha',      nameAr: 'أبها' },
    { name: 'Jubail',    nameAr: 'الجبيل' },
    { name: 'Dhahran',   nameAr: 'الظهران' },
    { name: 'Tabuk',     nameAr: 'تبوك' },
    { name: 'Khobar',    nameAr: 'الخبر' },
    { name: 'Dammam',    nameAr: 'الدمام' },
    { name: 'NEOM',      nameAr: 'نيوم' },
    { name: 'Al Ula',    nameAr: 'العُلا' },
    { name: 'Jeddah',    nameAr: 'جدة' },
    { name: 'Riyadh',    nameAr: 'الرياض' },
    { name: 'Mecca',     nameAr: 'مكة المكرمة' },
  ],
  [
    { name: 'King Khalid International',          nameAr: 'مطار الملك خالد الدولي' },
    { name: 'King Abdulaziz International',        nameAr: 'مطار الملك عبدالعزيز الدولي' },
    { name: 'King Fahd International',             nameAr: 'مطار الملك فهد الدولي' },
    { name: 'Prince Muhammad Bin Abdulaziz Intl', nameAr: 'مطار الأمير محمد بن عبدالعزيز' },
  ],
  [
    { name: 'Saudi Electricity',  nameAr: 'الكهرباء السعودية' },
    { name: 'National Water Co.', nameAr: 'الشركة الوطنية للمياه' },
  ],
  { name: 'Zakat al-Tijarah',   nameAr: 'زكاة التجارة',             amount: 500 },
  { name: 'Oil Revenue Tax',    nameAr: 'ضريبة الإيرادات النفطية',   amount: 2000 },
  { name: 'Vision 2030 Opportunity', nameAr: 'فرصة رؤية ٢٠٣٠' },
  { name: 'Saudi Dev. Fund',    nameAr: 'صندوق التنمية السعودي' },
);

// ─── Country: Syria ───────────────────────────────────────────────────────────
const SYRIA_BOARD = buildBoard(
  [
    { name: 'Al-Hasakah',         nameAr: 'الحسكة' },
    { name: 'Qamishli',           nameAr: 'القامشلي' },
    { name: 'Raqqa',              nameAr: 'الرقة' },
    { name: 'Idlib',              nameAr: 'إدلب' },
    { name: 'Daraa',              nameAr: 'درعا' },
    { name: 'Deir ez-Zor',        nameAr: 'دير الزور' },
    { name: 'Al-Suwayda',         nameAr: 'السويداء' },
    { name: 'Tartus',             nameAr: 'طرطوس' },
    { name: 'Hama',               nameAr: 'حماه' },
    { name: 'Homs',               nameAr: 'حمص' },
    { name: 'Latakia',            nameAr: 'اللاذقية' },
    { name: 'Maaloula',           nameAr: 'معلولا' },
    { name: 'Bosra',              nameAr: 'بصرى' },
    { name: 'Krak des Chevaliers',nameAr: 'قلعة الحصن' },
    { name: 'Ugarit',             nameAr: 'أوغاريت' },
    { name: 'Palmyra',            nameAr: 'تدمر' },
    { name: 'Aleppo',             nameAr: 'حلب' },
    { name: 'Aleppo Old City',    nameAr: 'حلب القديمة' },
    { name: 'Apamea',             nameAr: 'أفاميا' },
    { name: 'Damascus',           nameAr: 'دمشق' },
    { name: 'Damascus Old City',  nameAr: 'دمشق القديمة' },
    { name: 'Damascus CBD',       nameAr: 'قلب دمشق' },
  ],
  [
    { name: 'Damascus International Airport', nameAr: 'مطار دمشق الدولي' },
    { name: 'Aleppo International Airport',   nameAr: 'مطار حلب الدولي' },
    { name: 'Latakia Port Rail',              nameAr: 'سكة ميناء اللاذقية' },
    { name: 'Deir ez-Zor Airport',            nameAr: 'مطار دير الزور' },
  ],
  [
    { name: 'Syrian Electric Co.',     nameAr: 'الكهرباء السورية' },
    { name: 'Euphrates Water Auth.',   nameAr: 'هيئة مياه الفرات' },
  ],
  { name: 'Reconstruction Tax',     nameAr: 'ضريبة إعادة الإعمار',    amount: 500 },
  { name: 'Heritage Preservation',  nameAr: 'رسوم الحفاظ على التراث', amount: 2000 },
  { name: 'Desert Chance',          nameAr: 'حظ الصحراء' },
  { name: 'Syria Rebuild Fund',     nameAr: 'صندوق إعادة إعمار سوريا' },
);

// ─── Country: Gulf States ─────────────────────────────────────────────────────
const GULF_BOARD = buildBoard(
  [
    { name: 'Umm Al Quwain',      nameAr: 'أم القيوين' },
    { name: 'Sur',                nameAr: 'صور' },
    { name: 'Ajman',              nameAr: 'عجمان' },
    { name: 'Fujairah',           nameAr: 'الفجيرة' },
    { name: 'Ras Al Khaimah',     nameAr: 'رأس الخيمة' },
    { name: 'Salalah',            nameAr: 'صلالة' },
    { name: 'Muharraq',           nameAr: 'المحرق' },
    { name: 'Sohar',              nameAr: 'صحار' },
    { name: 'Muscat',             nameAr: 'مسقط' },
    { name: 'Manama',             nameAr: 'المنامة' },
    { name: 'Sharjah',            nameAr: 'الشارقة' },
    { name: 'Kuwait City',        nameAr: 'مدينة الكويت' },
    { name: 'Yas Island',         nameAr: 'جزيرة ياس' },
    { name: 'Lusail',             nameAr: 'لوسيل' },
    { name: 'The Pearl Qatar',    nameAr: 'لؤلؤة قطر' },
    { name: 'Saadiyat Island',    nameAr: 'جزيرة السعديات' },
    { name: 'Doha',               nameAr: 'الدوحة' },
    { name: 'Dubai Marina',       nameAr: 'مرسى دبي' },
    { name: 'DIFC Dubai',         nameAr: 'مركز دبي المالي الدولي' },
    { name: 'Palm Jumeirah',      nameAr: 'نخلة جميرا' },
    { name: 'Abu Dhabi CBD',      nameAr: 'مركز أبوظبي المالي' },
    { name: 'Dubai Downtown',     nameAr: 'وسط دبي' },
  ],
  [
    { name: 'Dubai International (DXB)',  nameAr: 'مطار دبي الدولي' },
    { name: 'Abu Dhabi International (AUH)', nameAr: 'مطار أبوظبي الدولي' },
    { name: 'Hamad International (DOH)',  nameAr: 'مطار حمد الدولي' },
    { name: 'Kuwait International Airport', nameAr: 'مطار الكويت الدولي' },
  ],
  [
    { name: 'Gulf Energy Corp.',     nameAr: 'شركة الطاقة الخليجية' },
    { name: 'Gulf Desalination Co.', nameAr: 'شركة تحلية الخليج' },
  ],
  { name: 'Gulf VAT',           nameAr: 'ضريبة القيمة المضافة الخليجية', amount: 500 },
  { name: 'Luxury Property Tax',nameAr: 'ضريبة العقارات الفاخرة',         amount: 2000 },
  { name: 'Gulf Opportunity',   nameAr: 'فرصة خليجية' },
  { name: 'Gulf Dev. Fund',     nameAr: 'صندوق التنمية الخليجي' },
);

// ─── Challenge: GCC (Gulf Cooperation Council) ────────────────────────────────
const GCC_BOARD = buildBoard(
  [
    { name: 'Al Khobar',        nameAr: 'الخبر' },
    { name: 'Sohar',            nameAr: 'صحار' },
    { name: 'Fujairah',         nameAr: 'الفجيرة' },
    { name: 'Ras Al Khaimah',   nameAr: 'رأس الخيمة' },
    { name: 'Salalah',          nameAr: 'صلالة' },
    { name: 'Muscat',           nameAr: 'مسقط' },
    { name: 'Al Ain',           nameAr: 'العين' },
    { name: 'Sharjah',          nameAr: 'الشارقة' },
    { name: 'Muscat CBD',       nameAr: 'مسقط المالي' },
    { name: 'The Pearl Qatar',  nameAr: 'لؤلؤة قطر' },
    { name: 'Lusail',           nameAr: 'لوسيل' },
    { name: 'Tabuk',            nameAr: 'تبوك' },
    { name: 'Dammam',           nameAr: 'الدمام' },
    { name: 'Jubail',           nameAr: 'الجبيل' },
    { name: 'NEOM',             nameAr: 'نيوم' },
    { name: 'Jeddah',           nameAr: 'جدة' },
    { name: 'Doha',             nameAr: 'الدوحة' },
    { name: 'Riyadh',           nameAr: 'الرياض' },
    { name: 'Dubai Marina',     nameAr: 'مرسى دبي' },
    { name: 'Palm Jumeirah',    nameAr: 'نخلة جميرا' },
    { name: 'Abu Dhabi',        nameAr: 'أبوظبي' },
    { name: 'Dubai Downtown',   nameAr: 'وسط دبي' },
  ],
  [
    { name: 'King Abdulaziz International', nameAr: 'مطار الملك عبدالعزيز' },
    { name: 'Dubai International (DXB)',    nameAr: 'مطار دبي الدولي' },
    { name: 'Hamad International (DOH)',    nameAr: 'مطار حمد الدولي' },
    { name: 'Muscat International (MCT)',   nameAr: 'مطار مسقط الدولي' },
  ],
  [
    { name: 'GCC Power Grid',     nameAr: 'الشبكة الكهربائية الخليجية' },
    { name: 'GCC Water Network',  nameAr: 'شبكة المياه الخليجية' },
  ],
  { name: 'GCC VAT',            nameAr: 'ضريبة القيمة المضافة',        amount: 500 },
  { name: 'Luxury Property Tax',nameAr: 'ضريبة العقارات الفاخرة',      amount: 2000 },
  { name: 'Gulf Opportunity',   nameAr: 'فرصة خليجية' },
  { name: 'GCC Dev. Fund',      nameAr: 'صندوق التنمية الخليجي' },
);

// ─── Challenge: Al Sham (Jordan, Syria, Lebanon) ───────────────────────────────
const AL_SHAM_BOARD = buildBoard(
  [
    { name: 'Zarqa',            nameAr: 'الزرقاء' },
    { name: 'Irbid',            nameAr: 'إربد' },
    { name: 'Tartus',           nameAr: 'طرطوس' },
    { name: 'Latakia',          nameAr: 'اللاذقية' },
    { name: 'Tripoli LB',       nameAr: 'طرابلس' },
    { name: 'Sidon',            nameAr: 'صيدا' },
    { name: 'Homs',             nameAr: 'حمص' },
    { name: 'Tyre',             nameAr: 'صور' },
    { name: 'Hama',             nameAr: 'حماه' },
    { name: 'Palmyra',          nameAr: 'تدمر' },
    { name: 'Krak des Chevaliers', nameAr: 'قلعة الحصن' },
    { name: 'Dead Sea',         nameAr: 'البحر الميت' },
    { name: 'Wadi Rum',         nameAr: 'وادي رم' },
    { name: 'Aqaba',            nameAr: 'العقبة' },
    { name: 'Aleppo',           nameAr: 'حلب' },
    { name: 'Byblos',           nameAr: 'جبيل' },
    { name: 'Petra',            nameAr: 'البتراء' },
    { name: 'Damascus',         nameAr: 'دمشق' },
    { name: 'Amman',            nameAr: 'عمّان' },
    { name: 'Beirut Downtown',  nameAr: 'وسط بيروت' },
    { name: 'Beirut Corniche',  nameAr: 'كورنيش بيروت' },
    { name: 'West Amman',       nameAr: 'غرب عمّان' },
  ],
  [
    { name: 'Queen Alia Intl Airport',  nameAr: 'مطار الملكة علياء' },
    { name: 'Damascus International',   nameAr: 'مطار دمشق الدولي' },
    { name: 'Beirut Rafic Hariri Intl', nameAr: 'مطار رفيق الحريري' },
    { name: 'Aleppo International',     nameAr: 'مطار حلب الدولي' },
  ],
  [
    { name: 'Levant Electric Co.',    nameAr: 'شركة كهرباء الشام' },
    { name: 'Jordan River Authority', nameAr: 'هيئة نهر الأردن' },
  ],
  { name: 'Income Tax',        nameAr: 'ضريبة الدخل',              amount: 500 },
  { name: 'Heritage Tax',      nameAr: 'رسوم الحفاظ على التراث',   amount: 2000 },
  { name: 'Sham Fortune',      nameAr: 'حظ بلاد الشام' },
  { name: 'Sham Dev. Fund',    nameAr: 'صندوق تنمية الشام' },
);

// ─── Challenge: North Africa ──────────────────────────────────────────────────
const NORTH_AFRICA_BOARD = buildBoard(
  [
    { name: 'Tobruk',           nameAr: 'طبرق' },
    { name: 'Benghazi',         nameAr: 'بنغازي' },
    { name: 'Bizerte',          nameAr: 'بنزرت' },
    { name: 'Sfax',             nameAr: 'صفاقس' },
    { name: 'Sousse',           nameAr: 'سوسة' },
    { name: 'Oran',             nameAr: 'وهران' },
    { name: 'Constantine',      nameAr: 'قسنطينة' },
    { name: 'Annaba',           nameAr: 'عنابة' },
    { name: 'Luxor',            nameAr: 'الأقصر' },
    { name: 'Aswan',            nameAr: 'أسوان' },
    { name: 'Port Said',        nameAr: 'بورسعيد' },
    { name: 'Tripoli LY',       nameAr: 'طرابلس الغرب' },
    { name: 'Fes',              nameAr: 'فاس' },
    { name: 'Marrakech',        nameAr: 'مراكش' },
    { name: 'Tunis',            nameAr: 'تونس' },
    { name: 'Algiers',          nameAr: 'الجزائر' },
    { name: 'Alexandria',       nameAr: 'الإسكندرية' },
    { name: 'Casablanca',       nameAr: 'الدار البيضاء' },
    { name: 'Cairo Old City',   nameAr: 'القاهرة التاريخية' },
    { name: 'Rabat',            nameAr: 'الرباط' },
    { name: 'Cairo Corniche',   nameAr: 'كورنيش القاهرة' },
    { name: 'Cairo CBD',        nameAr: 'قلب القاهرة' },
  ],
  [
    { name: 'Cairo International Airport', nameAr: 'مطار القاهرة الدولي' },
    { name: 'Mohammed V (CMN)',            nameAr: 'مطار محمد الخامس' },
    { name: 'Algiers Houari Boumediene',   nameAr: 'مطار هواري بومدين' },
    { name: 'Tunis-Carthage Airport',      nameAr: 'مطار تونس قرطاج' },
  ],
  [
    { name: 'Nile Delta Power',   nameAr: 'طاقة دلتا النيل' },
    { name: 'Maghreb Water Co.',  nameAr: 'شركة مياه المغرب العربي' },
  ],
  { name: 'Trade Tax',        nameAr: 'ضريبة التجارة',         amount: 500 },
  { name: 'Nile Revenue Tax', nameAr: 'ضريبة إيرادات النيل',  amount: 2000 },
  { name: 'Nile Fortune',     nameAr: 'حظ النيل' },
  { name: 'North Africa Fund',nameAr: 'صندوق شمال أفريقيا' },
);

// ─── Challenge: Iraq ──────────────────────────────────────────────────────────
const IRAQ_BOARD = buildBoard(
  [
    { name: 'Al-Fallujah',     nameAr: 'الفلوجة' },
    { name: 'Tikrit',          nameAr: 'تكريت' },
    { name: 'Kirkuk',          nameAr: 'كركوك' },
    { name: 'Ramadi',          nameAr: 'الرمادي' },
    { name: 'Al-Amarah',       nameAr: 'العمارة' },
    { name: 'Al-Nasiriyah',    nameAr: 'الناصرية' },
    { name: 'Mosul Old City',  nameAr: 'الموصل القديمة' },
    { name: 'Sulaymaniyah',    nameAr: 'السليمانية' },
    { name: 'Duhok',           nameAr: 'دهوك' },
    { name: 'Al-Hillah',       nameAr: 'الحلة' },
    { name: 'Kut',             nameAr: 'الكوت' },
    { name: 'Karbala',         nameAr: 'كربلاء' },
    { name: 'Najaf',           nameAr: 'النجف' },
    { name: 'Samarra',         nameAr: 'سامراء' },
    { name: 'Mosul',           nameAr: 'الموصل' },
    { name: 'Basra Port',      nameAr: 'ميناء البصرة' },
    { name: 'Erbil Modern',    nameAr: 'أربيل الحديثة' },
    { name: 'Basra CBD',       nameAr: 'قلب البصرة' },
    { name: 'Baghdad Al-Karkh',nameAr: 'بغداد الكرخ' },
    { name: 'Baghdad Al-Rusafa',nameAr: 'بغداد الرصافة' },
    { name: 'Baghdad Al-Mansour',nameAr: 'بغداد المنصور' },
    { name: 'Baghdad CBD',     nameAr: 'قلب بغداد' },
  ],
  [
    { name: 'Baghdad International Airport', nameAr: 'مطار بغداد الدولي' },
    { name: 'Basra International Airport',   nameAr: 'مطار البصرة الدولي' },
    { name: 'Erbil International Airport',   nameAr: 'مطار أربيل الدولي' },
    { name: 'Sulaymaniyah Airport',          nameAr: 'مطار السليمانية' },
  ],
  [
    { name: 'Diyala Water Authority', nameAr: 'هيئة مياه ديالى' },
    { name: 'Iraq National Grid',     nameAr: 'الشبكة الكهربائية العراقية' },
  ],
  { name: 'Oil Revenue Tax',   nameAr: 'ضريبة الإيرادات النفطية',  amount: 500 },
  { name: 'Reconstruction Tax',nameAr: 'ضريبة إعادة الإعمار',      amount: 2000 },
  { name: 'Tigris Fortune',    nameAr: 'حظ دجلة' },
  { name: 'Iraq Dev. Fund',    nameAr: 'صندوق التنمية العراقي' },
);

// ─── Registry ─────────────────────────────────────────────────────────────────
export const CHALLENGE_BOARDS: Record<string, BoardSpace[]> = {
  tech:         TECH_BOARD,
  fashion:      FASHION_BOARD,
  food:         FOOD_BOARD,
  defense:      DEFENSE_BOARD,
  jordan:       JORDAN_BOARD,
  saudi:        SAUDI_BOARD,
  syria:        SYRIA_BOARD,
  gulf:         GULF_BOARD,
  gcc:          GCC_BOARD,
  alsham:       AL_SHAM_BOARD,
  northafrica:  NORTH_AFRICA_BOARD,
  iraq:         IRAQ_BOARD,
};
