"""
Diagram 1 — the whole deployment in four boxes.

This is the "read this first" picture. It deliberately names no cloud service
and shows no settings: it exists so that someone looking at the AWS or Azure
page already knows what they are looking at, and why the single-server rule is
there. The detail lives in DEPLOYMENT_ARCHITECTURE.md.
"""

from __future__ import annotations

from pathlib import Path

from _canvas import PALETTE as P
from _canvas import Canvas

W, H = 1688, 660


def render(out_dir: Path) -> Path:
    c = Canvas(W, H)
    c.heading(
        "How Eastern Tycoon is deployed",
        "The whole picture, before any cloud service names. Follow 1 to 4.",
    )

    y, h, w = 170, 220, 339
    xs = [48, 465, 882, 1299]

    c.step(
        (xs[0], y, w, h),
        1,
        "Players",
        ["The app on iOS and Android", "A web browser (optional)"],
        accent=P["cyan"],
    )
    c.step(
        (xs[1], y, w, h),
        2,
        "Internet edge",
        ["Your domain name and HTTPS", "Firewall and rate limiting", "Load balancer"],
        accent=P["gold"],
    )
    c.step(
        (xs[2], y, w, h),
        3,
        "The API server",
        ["Runs the game rules", "Keeps every live game in memory", "Never more than one copy"],
        accent=P["green"],
        badge="ONLY ONE",
    )
    c.step(
        (xs[3], y, w, h),
        4,
        "Disk",
        ["A backup copy of the games", "Reloaded if the server restarts"],
        accent=P["blue"],
    )

    mid = y + h / 2
    for i in range(3):
        c.arrow([(xs[i] + w + 8, mid), (xs[i + 1] - 8, mid)], color=P["dim"])

    c.note(
        (48, 448, 1592, 124),
        "Why only one server?",
        "Live games are held in the server's memory, not in a database. A second server would keep its own "
        "separate copy of the board, so players connected to it would watch a game that never moves. "
        "Everything on the AWS and Azure pages exists to guarantee that exactly one server runs at a time.",
        accent=P["red"],
    )

    c.footnote("Generated by scripts/diagrams/d01_logical.py — edit the script, not the PNG.")
    return c.save(out_dir / "01-how-it-works.png")


if __name__ == "__main__":
    print(render(Path(__file__).resolve().parents[2] / "diagrams"))
