"""
Diagram 2 — Eastern Tycoon on AWS.

Same five-step shape as the Azure page so the two can be compared at a glance.
The request path is the top row and nothing else; anything not on the request
path is demoted to the quiet band below it, and only the three settings that a
default-configured deploy gets wrong appear as text.
"""

from __future__ import annotations

from pathlib import Path

from _canvas import PALETTE as P
from _canvas import Canvas

W, H = 1688, 850
AWS = P["aws"]


def render(out_dir: Path) -> Path:
    c = Canvas(W, H)
    c.heading(
        "Eastern Tycoon on AWS",
        "The request path, left to right. One task, always.",
        accent=AWS,
    )

    y, h, w = 170, 220, 273
    xs = [48, 377, 706, 1035, 1364]

    c.step((xs[0], y, w, h), 1, "Players", ["Phone app", "or web browser"], accent=P["cyan"])
    c.step(
        (xs[1], y, w, h),
        2,
        "Route 53",
        ["Your domain name", "Points at the load balancer"],
        accent=AWS,
    )
    c.step(
        (xs[2], y, w, h),
        3,
        "WAF + Load balancer",
        ["HTTPS ends here", "Blocks abusive traffic"],
        accent=AWS,
    )
    c.step(
        (xs[3], y, w, h),
        4,
        "ECS Fargate",
        ["Runs the API server", "Exactly one task"],
        accent=P["green"],
        badge="ONLY ONE",
    )
    c.step((xs[4], y, w, h), 5, "EFS", ["Saved games on disk", "Survives restarts"], accent=P["blue"])

    mid = y + h / 2
    for i in range(4):
        c.arrow([(xs[i] + w + 8, mid), (xs[i + 1] - 8, mid)], color=P["dim"])

    # ---- everything that is not on the request path -----------------------

    c.band((48, 440, 1592, 150), "Supporting services", accent=P["dim"])
    tiles = [
        (70, "ECR", "Stores the container image"),
        (462, "Secrets Manager", "API keys and allowed origins"),
        (854, "CloudWatch", "Logs and alerts"),
        (1246, "CloudFront + S3", "Serves the web version"),
    ]
    for x, title, line in tiles:
        c.tile((x, 488, 372, 76), title, line, accent=AWS)

    # ---- the settings a default deploy gets wrong -------------------------

    c.note(
        (48, 618, 1592, 160),
        "Three settings that keep it to one server",
        [
            "ECS deployment percentages 0% minimum / 100% maximum — the default (100/200) briefly runs the "
            "old and new task together, which is two copies of every live game.",
            "Load balancer idle timeout 60 seconds — the app holds a request open for up to 20 seconds while "
            "it waits for the other player's move.",
            "Task stop timeout 40 seconds and deregistration delay 30 seconds — the server needs up to 25 "
            "seconds to save games before it exits.",
        ],
        accent=AWS,
    )

    c.footnote(
        "Generated by scripts/diagrams/d02_aws.py — edit the script, not the PNG. "
        "Full settings and environment variables: DEPLOYMENT_ARCHITECTURE.md"
    )
    return c.save(out_dir / "02-aws-architecture.png")


if __name__ == "__main__":
    print(render(Path(__file__).resolve().parents[2] / "diagrams"))
