"""
Diagram 3 — Eastern Tycoon on Azure.

Deliberately the same five-step shape as d02_aws.py so the two pages can be put
side by side and compared box for box. Only the service names and the third
setting genuinely differ: ECS can be told never to run two tasks, while
Container Apps hands traffic over between revisions and has to be forced.
"""

from __future__ import annotations

from pathlib import Path

from _canvas import PALETTE as P
from _canvas import Canvas

W, H = 1688, 850
AZ = P["azure"]


def render(out_dir: Path) -> Path:
    c = Canvas(W, H)
    c.heading(
        "Eastern Tycoon on Azure",
        "The request path, left to right. One replica, always.",
        accent=AZ,
    )

    y, h, w = 170, 220, 273
    xs = [48, 377, 706, 1035, 1364]

    c.step((xs[0], y, w, h), 1, "Players", ["Phone app", "or web browser"], accent=P["cyan"])
    c.step(
        (xs[1], y, w, h),
        2,
        "Azure DNS",
        ["Your domain name", "Points at Front Door"],
        accent=AZ,
    )
    c.step(
        (xs[2], y, w, h),
        3,
        "Front Door + WAF",
        ["HTTPS ends here", "Blocks abusive traffic"],
        accent=AZ,
    )
    c.step(
        (xs[3], y, w, h),
        4,
        "Container Apps",
        ["Runs the API server", "Exactly one replica"],
        accent=P["green"],
        badge="ONLY ONE",
    )
    c.step(
        (xs[4], y, w, h),
        5,
        "Azure Files",
        ["Saved games on disk", "Survives restarts"],
        accent=P["blue"],
    )

    mid = y + h / 2
    for i in range(4):
        c.arrow([(xs[i] + w + 8, mid), (xs[i + 1] - 8, mid)], color=P["dim"])

    # ---- everything that is not on the request path -----------------------

    c.band((48, 440, 1592, 150), "Supporting services", accent=P["dim"])
    tiles = [
        (70, "Container Registry", "Stores the container image"),
        (462, "Key Vault", "API keys and allowed origins"),
        (854, "Log Analytics", "Logs and alerts"),
        (1246, "Static Web Apps", "Serves the web version"),
    ]
    for x, title, line in tiles:
        c.tile((x, 488, 372, 76), title, line, accent=AZ)

    # ---- the settings a default deploy gets wrong -------------------------

    c.note(
        (48, 618, 1592, 160),
        "Three settings that keep it to one server",
        [
            "Minimum and maximum replicas both set to 1, and no HTTP scale rule — a scale rule would add "
            "replicas under exactly the load you care about.",
            "Front Door origin timeout above 20 seconds — the app holds a request open that long while it "
            "waits for the other player's move.",
            "Deploy by scaling to 0 and back to 1 — Container Apps otherwise shifts traffic between revisions "
            "and briefly runs two. App Service enforces this natively with WEBSITE_DISABLE_OVERLAPPED_RECYCLING=1.",
        ],
        accent=AZ,
    )

    c.footnote(
        "Generated by scripts/diagrams/d03_azure.py — edit the script, not the PNG. "
        "Full settings and environment variables: DEPLOYMENT_ARCHITECTURE.md"
    )
    return c.save(out_dir / "03-azure-architecture.png")


if __name__ == "__main__":
    print(render(Path(__file__).resolve().parents[2] / "diagrams"))
