"""
Diagram 4 — what happens during a deploy, drawn to scale.

This is the page to point at when someone asks why the load balancer and
orchestrator timeouts on the AWS and Azure diagrams are set the way they are.
Every number comes from artifacts/api-server/src/config.ts (POLL_TIMEOUT_MS
20_000, SHUTDOWN_TIMEOUT_MS 25_000) and the shutdown sequence in src/index.ts.
"""

from __future__ import annotations

from pathlib import Path

from _canvas import PALETTE as P
from _canvas import Canvas, mix

W, H = 1688, 650

T0 = 470.0
T_END = 1620.0
SPAN_S = 45.0
PX_PER_S = (T_END - T0) / SPAN_S


def _x(seconds: float) -> float:
    return T0 + seconds * PX_PER_S


def render(out_dir: Path) -> Path:
    c = Canvas(W, H)
    c.heading(
        "What happens during a deploy",
        "Drawn to scale. Every bar has to finish inside the bar above it.",
        accent=P["amber"],
    )

    bars = [
        (180, 0.0, 40.0, "The platform waits for the old server", "40s", P["blue"]),
        (226, 0.0, 25.0, "The old server's shutdown deadline", "25s", P["amber"]),
        (272, 0.0, 20.0, "It finishes requests that are still open", "up to 20s", P["green"]),
        (318, 20.0, 23.0, "Then it saves the games to disk", "~3s", P["purple"]),
        (378, 25.0, 42.0, "The new server starts and goes live", "", P["cyan"]),
    ]

    for y, start, end, label, badge, color in bars:
        x0, x1 = _x(start), _x(end)
        c.text(450, y + 8, label, size=14.5, fill=P["muted"], anchor="ra")
        c.rrect((x0, y, x1 - x0, 34), radius=7, fill=mix(P["bg"], color, 0.32))
        c.rrect((x0, y, x1 - x0, 34), radius=7, outline=color, width=1.4)
        if badge:
            c.text(x1 - 14, y + 9, badge, style="bold", size=13, fill=color, anchor="ra")

    # Time axis
    axis_y = 442
    c.line((T0, axis_y), (T_END, axis_y), color=P["border"], width=1.4)
    for t in range(0, 50, 5):
        c.line((_x(t), axis_y - 5), (_x(t), axis_y + 5), color=P["border"], width=1.4)
        c.text(_x(t), axis_y + 13, f"{t}s", size=12.5, fill=P["dim"], anchor="ma")

    # The two moments that matter
    c.line((T0, 162), (T0, axis_y), color=P["red"], width=1.2)
    c.text(T0 + 8, 146, "Deploy starts", style="bold", size=13, fill=P["red"])
    c.line((_x(25), 162), (_x(25), axis_y), color=P["red"], width=1.2)
    c.text(_x(25) + 8, 146, "Old server is gone", style="bold", size=13, fill=P["red"])

    c.note(
        (48, 492, 1592, 110),
        "The tight spot",
        "A request can stay open for the full 20 seconds, which leaves only 5 seconds to save every game "
        "before the platform kills the server. If saving ever gets slower, raise the shutdown deadline "
        "(SHUTDOWN_TIMEOUT_MS) or shorten how long a request is held (POLL_TIMEOUT_MS).",
        accent=P["red"],
    )

    c.footnote(
        "Generated by scripts/diagrams/d04_lifecycle.py — edit the script, not the PNG. "
        "Timings from artifacts/api-server/src/config.ts."
    )
    return c.save(out_dir / "04-deploy-timeline.png")


if __name__ == "__main__":
    print(render(Path(__file__).resolve().parents[2] / "diagrams"))
