-- ============================================================
-- Dawaar – PostgreSQL Schema
-- ============================================================
-- Conventions:
--   * All primary keys are UUIDs generated by the database
--   * created_at / updated_at set via trigger
--   * Board data is stored as JSONB because its structure is
--     known and the array index IS the primary key (0-39)
-- ============================================================

-- ---------------------------------------------------------------------------
-- 1. Players  (persistent identity across games)
-- ---------------------------------------------------------------------------
CREATE TABLE players (
    id              UUID          PRIMARY KEY DEFAULT gen_random_uuid(),
    name            TEXT          NOT NULL,
    token           TEXT          NOT NULL,           -- e.g. 'camel', 'falcon'
    is_premium      BOOLEAN       NOT NULL DEFAULT FALSE,
    rc_customer_id  TEXT,                             -- RevenueCat customer ID (future)
    device_id       TEXT,                             -- anonymous device fingerprint
    created_at      TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ   NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- 2. Games
-- ---------------------------------------------------------------------------
CREATE TYPE game_status AS ENUM ('waiting', 'playing', 'finished');
CREATE TYPE game_mode   AS ENUM ('singleplayer', 'multiplayer');

CREATE TABLE games (
    id                  UUID          PRIMARY KEY DEFAULT gen_random_uuid(),
    short_code          TEXT          UNIQUE NOT NULL,   -- 6-char join code
    status              game_status   NOT NULL DEFAULT 'waiting',
    mode                game_mode     NOT NULL DEFAULT 'multiplayer',
    current_player_id   UUID          REFERENCES players(id),
    winner_id           UUID          REFERENCES players(id),
    has_rolled          BOOLEAN       NOT NULL DEFAULT FALSE,
    dice_roll           INTEGER[],                        -- e.g. {3,4}
    version             BIGINT        NOT NULL DEFAULT 0,
    max_players         SMALLINT      NOT NULL DEFAULT 4,
    -- pending trade is stored as JSON for simplicity; move to trades table for full audit
    pending_trade       JSONB,
    started_at          TIMESTAMPTZ,
    ended_at            TIMESTAMPTZ,
    created_at          TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ   NOT NULL DEFAULT now()
);

CREATE INDEX idx_games_short_code ON games (short_code);
CREATE INDEX idx_games_status     ON games (status);

-- ---------------------------------------------------------------------------
-- 3. Game Players  (join table — one row per player per game)
-- ---------------------------------------------------------------------------
CREATE TABLE game_players (
    id              UUID          PRIMARY KEY DEFAULT gen_random_uuid(),
    game_id         UUID          NOT NULL REFERENCES games(id) ON DELETE CASCADE,
    player_id       UUID          NOT NULL REFERENCES players(id),
    seat_order      SMALLINT      NOT NULL,             -- turn order (0-based)
    is_npc          BOOLEAN       NOT NULL DEFAULT FALSE,
    token           TEXT          NOT NULL,
    color           TEXT          NOT NULL,             -- hex e.g. '#EF4444'
    money           INTEGER       NOT NULL DEFAULT 15000,
    position        SMALLINT      NOT NULL DEFAULT 0,
    in_jail         BOOLEAN       NOT NULL DEFAULT FALSE,
    jail_turns      SMALLINT      NOT NULL DEFAULT 0,
    is_bankrupt     BOOLEAN       NOT NULL DEFAULT FALSE,
    doubles_count   SMALLINT      NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ   NOT NULL DEFAULT now(),
    UNIQUE (game_id, player_id),
    UNIQUE (game_id, seat_order)
);

CREATE INDEX idx_game_players_game ON game_players (game_id);

-- ---------------------------------------------------------------------------
-- 4. Board State  (one row per property per game)
-- ---------------------------------------------------------------------------
CREATE TABLE board_properties (
    id              UUID          PRIMARY KEY DEFAULT gen_random_uuid(),
    game_id         UUID          NOT NULL REFERENCES games(id) ON DELETE CASCADE,
    board_index     SMALLINT      NOT NULL CHECK (board_index BETWEEN 0 AND 39),
    name            TEXT          NOT NULL,
    name_ar         TEXT          NOT NULL,
    type            TEXT          NOT NULL,             -- 'property','railroad','utility','tax',etc.
    color_group     TEXT,
    price           INTEGER,
    mortgage_value  INTEGER,
    house_cost      INTEGER,
    hotel_cost      INTEGER,
    rent            INTEGER[],                          -- [base,1h,2h,3h,4h,hotel]
    railroad_rent   INTEGER[],                          -- [1,2,3,4 owned]
    tax_amount      INTEGER,
    owner_id        UUID          REFERENCES game_players(id),
    houses          SMALLINT      NOT NULL DEFAULT 0 CHECK (houses BETWEEN 0 AND 4),
    hotel           BOOLEAN       NOT NULL DEFAULT FALSE,
    is_mortgaged    BOOLEAN       NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ   NOT NULL DEFAULT now(),
    UNIQUE (game_id, board_index)
);

CREATE INDEX idx_board_props_game ON board_properties (game_id);

-- ---------------------------------------------------------------------------
-- 5. Game Log  (append-only event history)
-- ---------------------------------------------------------------------------
CREATE TABLE game_logs (
    id              BIGSERIAL     PRIMARY KEY,
    game_id         UUID          NOT NULL REFERENCES games(id) ON DELETE CASCADE,
    game_player_id  UUID          REFERENCES game_players(id),
    message         TEXT          NOT NULL,
    event_type      TEXT,         -- optional tag: 'roll','buy','jail','card','trade',etc.
    payload         JSONB,        -- optional structured data
    version_at      BIGINT,       -- game version when this event was recorded
    created_at      TIMESTAMPTZ   NOT NULL DEFAULT now()
);

CREATE INDEX idx_game_logs_game       ON game_logs (game_id, created_at);
CREATE INDEX idx_game_logs_game_ver   ON game_logs (game_id, version_at);

-- ---------------------------------------------------------------------------
-- 6. Trades  (completed trade audit trail)
-- ---------------------------------------------------------------------------
CREATE TYPE trade_status AS ENUM ('pending', 'accepted', 'rejected', 'expired');

CREATE TABLE trades (
    id                      UUID          PRIMARY KEY DEFAULT gen_random_uuid(),
    game_id                 UUID          NOT NULL REFERENCES games(id) ON DELETE CASCADE,
    from_player_id          UUID          NOT NULL REFERENCES game_players(id),
    to_player_id            UUID          NOT NULL REFERENCES game_players(id),
    offered_property_indices  SMALLINT[],               -- board indices
    requested_property_indices SMALLINT[],
    offered_money           INTEGER       NOT NULL DEFAULT 0,
    requested_money         INTEGER       NOT NULL DEFAULT 0,
    status                  trade_status  NOT NULL DEFAULT 'pending',
    resolved_at             TIMESTAMPTZ,
    created_at              TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at              TIMESTAMPTZ   NOT NULL DEFAULT now()
);

CREATE INDEX idx_trades_game ON trades (game_id);

-- ---------------------------------------------------------------------------
-- 7. Chance / Community Cards  (shuffled deck per game — optional)
-- ---------------------------------------------------------------------------
CREATE TABLE game_decks (
    id          UUID          PRIMARY KEY DEFAULT gen_random_uuid(),
    game_id     UUID          NOT NULL REFERENCES games(id) ON DELETE CASCADE,
    deck_type   TEXT          NOT NULL CHECK (deck_type IN ('chance', 'community')),
    card_order  INTEGER[]     NOT NULL,   -- shuffled indices into the static card arrays
    draw_index  SMALLINT      NOT NULL DEFAULT 0,
    created_at  TIMESTAMPTZ   NOT NULL DEFAULT now(),
    UNIQUE (game_id, deck_type)
);

-- ---------------------------------------------------------------------------
-- 8. updated_at auto-update trigger
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_players_updated          BEFORE UPDATE ON players          FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_games_updated            BEFORE UPDATE ON games            FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_game_players_updated     BEFORE UPDATE ON game_players     FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_board_properties_updated BEFORE UPDATE ON board_properties FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_trades_updated           BEFORE UPDATE ON trades           FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- 9. Helpful views
-- ---------------------------------------------------------------------------

-- Active games with player count
CREATE VIEW active_games AS
SELECT
    g.id,
    g.short_code,
    g.status,
    g.mode,
    g.version,
    COUNT(gp.id) FILTER (WHERE NOT gp.is_npc AND NOT gp.is_bankrupt) AS human_players,
    COUNT(gp.id) AS total_players,
    g.created_at
FROM games g
LEFT JOIN game_players gp ON gp.game_id = g.id
WHERE g.status <> 'finished'
GROUP BY g.id;

-- Per-game leaderboard snapshot
CREATE VIEW game_leaderboard AS
SELECT
    gp.game_id,
    p.name,
    gp.token,
    gp.color,
    gp.money,
    gp.is_bankrupt,
    gp.seat_order,
    COUNT(bp.id) AS properties_owned
FROM game_players gp
JOIN players p ON p.id = gp.player_id
LEFT JOIN board_properties bp ON bp.game_id = gp.game_id AND bp.owner_id = gp.id
GROUP BY gp.game_id, gp.id, p.name, gp.token, gp.color, gp.money, gp.is_bankrupt, gp.seat_order
ORDER BY gp.game_id, gp.money DESC;
